"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { createContext, useState } from "react";
import Button from "@/components/Button";

// const darkModeContext = createContext(false);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${darkMode ? "bg-black" : "bg-white"} antialiased`}
      >
        <header className="flex items-center justify-between p-4">
          <Button onclick={() => setDarkMode(!darkMode)} label="dark mode" />
        </header>
        {children}
      </body>
    </html>
  );
}
